# Generated by Django 5.2.13 on 2026-07-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carrinho',
            options={'verbose_name': 'Carrinho', 'verbose_name_plural': 'Carrinhos'},
        ),
        migrations.AlterModelOptions(
            name='categoriaprodutos',
            options={'ordering': ['nome_categoria'], 'verbose_name': 'Categoria de Produto', 'verbose_name_plural': 'Categorias de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='itemcarrinho',
            options={'verbose_name': 'Item do Carrinho', 'verbose_name_plural': 'Itens do Carrinho'},
        ),
        migrations.AlterModelOptions(
            name='itempedido',
            options={'verbose_name': 'Item do Pedido', 'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterModelOptions(
            name='pedido',
            options={'ordering': ['-criacao'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome_produto'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='projeto',
            options={'ordering': ['-criacao'], 'verbose_name': 'Projeto', 'verbose_name_plural': 'Projetos'},
        ),
        migrations.AlterField(
            model_name='imagemproduto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/'),
        ),
        migrations.AlterField(
            model_name='imagemprojeto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='projetos/'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='endereco',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='core.categoriaprodutos'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao_produto',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='cliente',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('PRODUTO', 'Produto'), ('PROJETO', 'Projeto'), ('MISTO', 'Misto')], default='MISTO', max_length=10)),
                ('status', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ENVIADO', 'Enviado'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('EXPIRADO', 'Expirado')], default='RASCUNHO', max_length=10)),
                ('cliente_nome', models.CharField(blank=True, default='', max_length=150)),
                ('cliente_email', models.EmailField(blank=True, default='', max_length=254)),
                ('cliente_telefone', models.CharField(blank=True, default='', max_length=20)),
                ('data_validade', models.DateField(blank=True, null=True)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observacoes', models.TextField(blank=True, default='')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-criacao'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, default='', max_length=200)),
                ('data_referencia', models.DateField(blank=True, help_text='Data prevista de execução/entrega deste item', null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='core.produto')),
                ('projeto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='core.projeto')),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.orcamento')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
                'ordering': ['id'],
            },
        ),
    ]
