# Generated by Django 5.2.8 on 2026-07-07 13:39

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_carrinho_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagemproduto',
            options={'verbose_name': 'Imagem de Produto', 'verbose_name_plural': 'Imagens de Produtos'},
        ),
        migrations.AlterModelOptions(
            name='imagemprojeto',
            options={'verbose_name': 'Imagem de Projeto', 'verbose_name_plural': 'Imagens de Projetos'},
        ),
        migrations.AddField(
            model_name='itemorcamento',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo unitário estimado para cálculo de lucro.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='itempedido',
            name='custo_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo unitário congelado no momento do pedido.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='custo_extra',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custos adicionais do orçamento, como frete, instalação, mão de obra ou deslocamento.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='data_prevista_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto'), ('A_COMBINAR', 'A combinar')], default='A_COMBINAR', max_length=20),
        ),
        migrations.AddField(
            model_name='orcamento',
            name='prazo_execucao',
            field=models.CharField(blank=True, default='', help_text='Exemplo: 30 dias úteis, 2 a 3 dias de instalação.', max_length=120),
        ),
        migrations.AddField(
            model_name='pedido',
            name='custo_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo total interno do pedido.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('DINHEIRO', 'Dinheiro'), ('TRANSFERENCIA', 'Transferência'), ('BOLETO', 'Boleto'), ('A_COMBINAR', 'A combinar')], default='A_COMBINAR', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='observacoes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='produto',
            name='custo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo interno do produto para cálculo de lucro.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projeto',
            name='custo_estimado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Custo interno estimado do projeto.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='projeto',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor de venda estimado do projeto.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='data_referencia',
            field=models.DateField(blank=True, help_text='Data prevista de execução/entrega deste item.', null=True),
        ),
        migrations.AlterField(
            model_name='itemorcamento',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='desconto_percentual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='avaliacao',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterUniqueTogether(
            name='itemcarrinho',
            unique_together={('carrinho', 'produto')},
        ),
    ]
