# Generated by Django 5.2.8 on 2026-09-09 13:37

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagemproduto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='pedido',
            name='cupom_codigo',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pedido',
            name='desconto_cupom',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('percentual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promocoes', to='core.produto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativo', models.BooleanField(default=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=150)),
                ('url', models.URLField(help_text='Link HTTPS de vídeo MP4/WebM hospedado. Não use link da página do YouTube.')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.projeto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
